apiVersion: apps/v1
kind: Deployment
metadata:
  name: random-api

spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
        - name: random-api
          image: docker.io/kubamater/openshift-random-api:latest
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          resources:
            requests:
              memory: "50Mi"
              cpu: "10m"


---
kind: Service
apiVersion: v1
metadata:
  name: random-api
spec:
  ports:
    - name: http-8081
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: python-app

---

apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: random-api
spec:
  host: random-api-random-api.apps-crc.testing
  port:
    targetPort: 8081 
  to:
    kind: Service
    name: random-api
